#!/usr/bin/env python3
"""
Configuration and constants for PULSE.
Package Utilities & Linux System Engine
Contains theme settings, application catalog, and UI constants.
"""
from pathlib import Path

# ==========================================
# FILE SYSTEM PATHS
# ==========================================

CONFIG_DIR = Path.home() / ".config" / "pulse"
LOG_DIR = Path.home() / ".local" / "share" / "pulse"
CONFIG_FILE = CONFIG_DIR / "settings.json"

# ==========================================
# VALIDATION CONSTANTS
# ==========================================

VALID_LOG_TYPES = ["info", "success", "warn", "error"]
MAX_DISPLAY_PACKAGES = 50
DESKTOP_ENTRY_PERMISSIONS = 0o755  # rwxr-xr-x
DIRECTORY_PERMISSIONS = 0o755

# ==========================================
# THEME CONFIGURATION
# ==========================================

THEME = {
    "bg": "#0d1117",
    "fg": "#c9d1d9",
    "accent": "#58a6ff",
    "success": "#3fb950",
    "warning": "#d29922",
    "error": "#f85149",
    "panel": "#161b22",
    "font_main": ("Courier New", 10),
    "font_header": ("Courier New", 14, "bold"),
    "font_ascii": ("Courier New", 8)
}

# ==========================================
# ASCII HEADER
# ==========================================

ASCII_HEADER = r"""
  ██████╗ ██╗   ██╗██╗     ███████╗███████╗
  ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
  ██████╔╝██║   ██║██║     ███████╗█████╗  
  ██╔═══╝ ██║   ██║██║     ╚════██║██╔══╝  
  ██║     ╚██████╔╝███████╗███████║███████╗
  ╚═╝      ╚═════╝ ╚══════╝╚══════╝╚══════╝
  >> Package Utilities & Linux System Engine <<
"""

# ==========================================
# APPLICATION CATALOG
# ==========================================
# Organized by category for tab-based UI
# Format: "Display Name": {"pkg": "package-name"}

APPS = {
    "INTERNET & SOCIAL": {
        "Chromium": {"pkg": "chromium-browser"},
        "Lynx": {"pkg": "lynx"},
        "W3M": {"pkg": "w3m"},
        "Links": {"pkg": "links"},
        "Tor Browser Launcher": {"pkg": "torbrowser-launcher"},
        "Thunderbird": {"pkg": "thunderbird"},
        "Evolution": {"pkg": "evolution"},
        "Geary": {"pkg": "geary"},
        "Mutt": {"pkg": "mutt"},
        "Claws Mail": {"pkg": "claws-mail"},
        "Transmission": {"pkg": "transmission"},
        "qBittorrent": {"pkg": "qbittorrent"},
        "Deluge": {"pkg": "deluge"},
        "Aria2": {"pkg": "aria2"},
        "FileZilla": {"pkg": "filezilla"},
        "HexChat": {"pkg": "hexchat"},
        "Irssi": {"pkg": "irssi"},
        "Weechat": {"pkg": "weechat"},
        "Pidgin": {"pkg": "pidgin"},
        "Empathy": {"pkg": "empathy"},
        "Remmina": {"pkg": "remmina"},
        "Vinagre": {"pkg": "vinagre"},
        "Teamviewer": {"pkg": "teamviewer"},
        "AnyDesk": {"pkg": "anydesk"},
        "KRDC": {"pkg": "krdc"},
        "Konversation": {"pkg": "konversation"},
        "Xchat": {"pkg": "xchat"},
        "Newsboat": {"pkg": "newsboat"},
        "Liferea": {"pkg": "liferea"},
        "RSS Guard": {"pkg": "rssguard"}
    },
    "MEDIA & DESIGN": {
        "VLC": {"pkg": "vlc"},
        "MPV": {"pkg": "mpv"},
        "SMPlayer": {"pkg": "smplayer"},
        "MPlayer": {"pkg": "mplayer"},
        "Celluloid": {"pkg": "celluloid"},
        "Parole": {"pkg": "parole"},
        "Totem": {"pkg": "totem"},
        "Dragon Player": {"pkg": "dragonplayer"},
        "Kdenlive": {"pkg": "kdenlive"},
        "OpenShot": {"pkg": "openshot-qt"},
        "Pitivi": {"pkg": "pitivi"},
        "Flowblade": {"pkg": "flowblade"},
        "Audacity": {"pkg": "audacity"},
        "Ardour": {"pkg": "ardour"},
        "LMMS": {"pkg": "lmms"},
        "MuseScore": {"pkg": "musescore3"},
        "Hydrogen": {"pkg": "hydrogen"},
        "Rosegarden": {"pkg": "rosegarden"},
        "HandBrake": {"pkg": "handbrake"},
        "FFmpeg": {"pkg": "ffmpeg"},
        "GIMP": {"pkg": "gimp"},
        "Inkscape": {"pkg": "inkscape"},
        "Krita": {"pkg": "krita"},
        "Blender": {"pkg": "blender"},
        "FreeCAD": {"pkg": "freecad"},
        "OpenSCAD": {"pkg": "openscad"},
        "Darktable": {"pkg": "darktable"},
        "RawTherapee": {"pkg": "rawtherapee"},
        "DigiKam": {"pkg": "digikam"},
        "Shotwell": {"pkg": "shotwell"},
        "gThumb": {"pkg": "gthumb"},
        "Scribus": {"pkg": "scribus"},
        "Synfig": {"pkg": "synfig"},
        "MyPaint": {"pkg": "mypaint"},
        "Pinta": {"pkg": "pinta"},
        "Kolourpaint": {"pkg": "kolourpaint"},
        "Rhythmbox": {"pkg": "rhythmbox"},
        "Clementine": {"pkg": "clementine"},
        "Amarok": {"pkg": "amarok"},
        "Banshee": {"pkg": "banshee"},
        "Audacious": {"pkg": "audacious"},
        "Quod Libet": {"pkg": "quodlibet"},
        "Cantata": {"pkg": "cantata"},
        "SuperTuxKart": {"pkg": "supertuxkart"},
        "Minetest": {"pkg": "minetest"},
        "0 A.D.": {"pkg": "0ad"},
        "Battle for Wesnoth": {"pkg": "wesnoth"},
        "Frozen Bubble": {"pkg": "frozen-bubble"},
        "Extreme Tux Racer": {"pkg": "extremetuxracer"},
        "Neverball": {"pkg": "neverball"},
        "Pingus": {"pkg": "pingus"}
    },
    "DEVELOPMENT": {
        "Atom": {"pkg": "atom"},
        "Kate": {"pkg": "kate"},
        "Gedit": {"pkg": "gedit"},
        "Pluma": {"pkg": "pluma"},
        "Mousepad": {"pkg": "mousepad"},
        "Git": {"pkg": "git"},
        "GitKraken": {"pkg": "gitkraken"},
        "Meld": {"pkg": "meld"},
        "DiffUse": {"pkg": "diffuse"},
        "Python3": {"pkg": "python3"},
        "Python3 Dev": {"pkg": "python3-dev"},
        "Pip": {"pkg": "python3-pip"},
        "IPython": {"pkg": "ipython3"},
        "IDLE": {"pkg": "idle3"},
        "PyCharm CE": {"pkg": "pycharm-community"},
        "Node.js": {"pkg": "nodejs"},
        "NPM": {"pkg": "npm"},
        "Yarn": {"pkg": "yarn"},
        "Docker": {"pkg": "docker.io"},
        "Docker Compose": {"pkg": "docker-compose"},
        "Podman": {"pkg": "podman"},
        "GoLang": {"pkg": "golang"},
        "Rust": {"pkg": "rustc"},
        "Cargo": {"pkg": "cargo"},
        "OpenJDK 11": {"pkg": "openjdk-11-jdk"},
        "OpenJDK 17": {"pkg": "openjdk-17-jdk"},
        "GCC": {"pkg": "gcc"},
        "G++": {"pkg": "g++"},
        "Clang": {"pkg": "clang"},
        "Make": {"pkg": "make"},
        "Autotools": {"pkg": "autotools-dev"},
        "Geany": {"pkg": "geany"},
        "Vim": {"pkg": "vim"},
        "Neovim": {"pkg": "neovim"},
        "Emacs": {"pkg": "emacs"},
        "Nano": {"pkg": "nano"},
        "CMake": {"pkg": "cmake"},
        "Qt Creator": {"pkg": "qtcreator"},
        "Code::Blocks": {"pkg": "codeblocks"},
        "Eclipse": {"pkg": "eclipse"},
        "NetBeans": {"pkg": "netbeans"},
        "Anjuta": {"pkg": "anjuta"},
        "Lazarus": {"pkg": "lazarus"},
        "MonoDevelop": {"pkg": "monodevelop"},
        "DB Browser": {"pkg": "sqlitebrowser"},
        "MySQL Workbench": {"pkg": "mysql-workbench"},
        "DBeaver": {"pkg": "dbeaver-ce"},
        "Bless Hex Editor": {"pkg": "bless"},
        "GHex": {"pkg": "ghex"},
        "Wireshark": {"pkg": "wireshark"},
        "Nmap": {"pkg": "nmap"},
        "Zenmap": {"pkg": "zenmap"},
        "Ettercap": {"pkg": "ettercap-graphical"},
        "VirtualBox": {"pkg": "virtualbox"},
        "QEMU": {"pkg": "qemu-system"},
        "Virt Manager": {"pkg": "virt-manager"},
        "Vagrant": {"pkg": "vagrant"},
        "Ansible": {"pkg": "ansible"},
        "Terraform": {"pkg": "terraform"},
        "Packer": {"pkg": "packer"}
    },
    "OFFICE & SCHOOL": {
        "LibreOffice": {"pkg": "libreoffice"},
        "LibreOffice Writer": {"pkg": "libreoffice-writer"},
        "LibreOffice Calc": {"pkg": "libreoffice-calc"},
        "LibreOffice Impress": {"pkg": "libreoffice-impress"},
        "Calligra Suite": {"pkg": "calligra"},
        "AbiWord": {"pkg": "abiword"},
        "Gnumeric": {"pkg": "gnumeric"},
        "FocusWriter": {"pkg": "focuswriter"},
        "Ghostwriter": {"pkg": "ghostwriter"},
        "ReText": {"pkg": "retext"},
        "Zim": {"pkg": "zim"},
        "CherryTree": {"pkg": "cherrytree"},
        "Joplin": {"pkg": "joplin"},
        "Calibre": {"pkg": "calibre"},
        "Okular": {"pkg": "okular"},
        "Evince": {"pkg": "evince"},
        "Atril": {"pkg": "atril"},
        "Xreader": {"pkg": "xreader"},
        "Zathura": {"pkg": "zathura"},
        "MuPDF": {"pkg": "mupdf"},
        "Xournal++": {"pkg": "xournalpp"},
        "Rnote": {"pkg": "rnote"},
        "GnuCash": {"pkg": "gnucash"},
        "HomeBank": {"pkg": "homebank"},
        "KMyMoney": {"pkg": "kmymoney"},
        "Money Manager Ex": {"pkg": "moneymanagerex"},
        "TexMaker": {"pkg": "texmaker"},
        "TeXstudio": {"pkg": "texstudio"},
        "Kile": {"pkg": "kile"},
        "LyX": {"pkg": "lyx"},
        "Texworks": {"pkg": "texworks"},
        "Stellarium": {"pkg": "stellarium"},
        "Celestia": {"pkg": "celestia"},
        "KStars": {"pkg": "kstars"},
        "Marble": {"pkg": "marble"},
        "KiCad": {"pkg": "kicad"},
        "Fritzing": {"pkg": "fritzing"},
        "CircuitJS": {"pkg": "circuitjs1"},
        "Qucs": {"pkg": "qucs"},
        "Octave": {"pkg": "octave"},
        "SciLab": {"pkg": "scilab"},
        "Maxima": {"pkg": "wxmaxima"},
        "GeoGebra": {"pkg": "geogebra"},
        "R": {"pkg": "r-base"},
        "RStudio": {"pkg": "rstudio"},
        "Anki": {"pkg": "anki"},
        "Mnemosyne": {"pkg": "mnemosyne"},
        "Klavaro": {"pkg": "klavaro"},
        "Tux Typing": {"pkg": "tuxtype"},
        "GCompris": {"pkg": "gcompris-qt"}
    },
    "SYSTEM & UTILS": {
        "Htop": {"pkg": "htop"},
        "Btop": {"pkg": "btop"},
        "Glances": {"pkg": "glances"},
        "Atop": {"pkg": "atop"},
        "Iotop": {"pkg": "iotop"},
        "Nmon": {"pkg": "nmon"},
        "Neofetch": {"pkg": "neofetch"},
        "Screenfetch": {"pkg": "screenfetch"},
        "Bashtop": {"pkg": "bashtop"},
        "GParted": {"pkg": "gparted"},
        "KDE Partition": {"pkg": "partitionmanager"},
        "GNOME Disks": {"pkg": "gnome-disk-utility"},
        "Synaptic": {"pkg": "synaptic"},
        "Timeshift": {"pkg": "timeshift"},
        "Deja Dup": {"pkg": "deja-dup"},
        "Rsync": {"pkg": "rsync"},
        "Grsync": {"pkg": "grsync"},
        "BleachBit": {"pkg": "bleachbit"},
        "Stacer": {"pkg": "stacer"},
        "Wine": {"pkg": "wine"},
        "PlayOnLinux": {"pkg": "playonlinux"},
        "Lutris": {"pkg": "lutris"},
        "Midnight Commander": {"pkg": "mc"},
        "Ranger": {"pkg": "ranger"},
        "Nnn": {"pkg": "nnn"},
        "Vifm": {"pkg": "vifm"},
        "PCManFM": {"pkg": "pcmanfm"},
        "Thunar": {"pkg": "thunar"},
        "Nautilus": {"pkg": "nautilus"},
        "Dolphin": {"pkg": "dolphin"},
        "Nemo": {"pkg": "nemo"},
        "Tree": {"pkg": "tree"},
        "Curl": {"pkg": "curl"},
        "Wget": {"pkg": "wget"},
        "Aria2c": {"pkg": "aria2"},
        "7Zip": {"pkg": "p7zip-full"},
        "Unrar": {"pkg": "unrar"},
        "Unzip": {"pkg": "unzip"},
        "Zip": {"pkg": "zip"},
        "PeaZip": {"pkg": "peazip"},
        "Ark": {"pkg": "ark"},
        "File Roller": {"pkg": "file-roller"},
        "FlameShot": {"pkg": "flameshot"},
        "Shutter": {"pkg": "shutter"},
        "Spectacle": {"pkg": "spectacle"},
        "GNOME Screenshot": {"pkg": "gnome-screenshot"},
        "Scrot": {"pkg": "scrot"},
        "Kazam": {"pkg": "kazam"},
        "SimpleScreenRecorder": {"pkg": "simplescreenrecorder"},
        "Terminator": {"pkg": "terminator"},
        "Tilix": {"pkg": "tilix"},
        "Kitty": {"pkg": "kitty"},
        "Alacritty": {"pkg": "alacritty"},
        "Konsole": {"pkg": "konsole"},
        "GNOME Terminal": {"pkg": "gnome-terminal"},
        "XFCE Terminal": {"pkg": "xfce4-terminal"},
        "Guake": {"pkg": "guake"},
        "Tilda": {"pkg": "tilda"},
        "Yakuake": {"pkg": "yakuake"},
        "Zsh": {"pkg": "zsh"},
        "Fish": {"pkg": "fish"},
        "Tmux": {"pkg": "tmux"},
        "Screen": {"pkg": "screen"},
        "UFW": {"pkg": "ufw"},
        "GUFW": {"pkg": "gufw"},
        "Firewall Config": {"pkg": "firewall-config"},
        "ClamAV": {"pkg": "clamav"},
        "ClamTk": {"pkg": "clamtk"},
        "Fail2Ban": {"pkg": "fail2ban"},
        "RKHunter": {"pkg": "rkhunter"},
        "Chkrootkit": {"pkg": "chkrootkit"},
        "Lynis": {"pkg": "lynis"},
        "OpenSSH Server": {"pkg": "openssh-server"},
        "OpenSSH Client": {"pkg": "openssh-client"},
        "Telnet": {"pkg": "telnet"},
        "FTP": {"pkg": "ftp"},
        "SSHFS": {"pkg": "sshfs"},
        "NFS Common": {"pkg": "nfs-common"},
        "Samba": {"pkg": "samba"},
        "Redshift": {"pkg": "redshift"},
        "F.lux Indicator": {"pkg": "fluxgui"},
        "Caffeine": {"pkg": "caffeine"},
        "Albert": {"pkg": "albert"},
        "Ulauncher": {"pkg": "ulauncher"},
        "Rofi": {"pkg": "rofi"},
        "Conky": {"pkg": "conky-all"},
        "Variety": {"pkg": "variety"},
        "Nitrogen": {"pkg": "nitrogen"},
        "Feh": {"pkg": "feh"}
    }
}
